### ISSUE TITLE
supports clip coupons from HEB

### ISSUE THREAD

**Issue by yxs** [buy/amex-offer-collector#6]
Hi,
I understand you may have a development roadmap, and I respect your priorities.
HEB's products are not banking-related, but expanding the offer collection feature to grocery stores might be worth considering.

https://www.heb.com/digital-coupon/coupon-selection/all-coupons

**Comment by buy** [comment]
Hi @yxs , thanks for the suggestion! I've added the support for HEB and Safeway, which should be available once the new version is published. Enjoy!
