### ISSUE TITLE
Support Kroger

### ISSUE THREAD

**Issue by yxs** [buy/amex-offer-collector#7]
Please consider adding a feature to support collecting coupons from the large grocery store, Kroger.

**Comment by buy** [comment]
@yxs absolutely, that should be a good one on the list, will add it this weekend or once I get a chance.

**Comment by buy** [comment]
@yxs done, will be available in the next release once Google approves it (v1.8.0)

![image](https://github.com/buy/amex-offer-collector/assets/1431965/12d203f2-5e0f-404f-9cc7-6a9096f9bcec)

**Comment by buy** [comment]
Implemented.
